<a href="https://colab.research.google.com/github/khd0303/Week13/blob/main/WEEK13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#lab11-1
#1
a = np.array([0,1,2,3,4,5,6,7,8,9])
a
#2

b = np.array(range(0,10))
b

#3

c = np.array(range(0,10,2))
c

#4

print('c.shape=',c.shape)
print('c.ndim=',c.ndim)
print('c.dtype=',c.dtype)
print('c.size=',c.size)
print('c.itemsize=',c.itemsize)

c.shape= (5,)
c.ndim= 1
c.dtype= int64
c.size= 5
c.itemsize= 8


In [ ]:
#lab11-2

#1
a = np.array([23,45,67,7,2,30,34,82])
print('a = array',a)

print('최댓값',a.max())
print('최솟값',a.min())
print('평균',a.mean())


#2

b = np.random.randint(0,99,size = 10)

print('b =' ,b)
print('최댓값',b.max())
print('최솟값',b.min())
print('평균',b.mean())

#3

c = np.append(a,b)

print('c : ',c)

a = array [23 45 67  7  2 30 34 82]
최댓값 82
최솟값 2
평균 36.25
b = [82 55 13 40 13 26 69 62 87 19]
최댓값 87
최솟값 13
평균 46.6
c :  [23 45 67  7  2 30 34 82 82 55 13 40 13 26 69 62 87 19]


In [ ]:
#lab11-3
#1

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a :',a,sep ='')
b = np.array([[2,2,2],[2,2,2],[2,2,2]])
print('b :',b,sep ='')

#2

print('a+b:',a+b,sep ='')
print('a-b:',a-b,sep ='')
print('a*b:',a*b,sep ='')
print('a/b:',a/b,sep ='')
print('a@b:',a@b,sep ='')
print('a**2:',a**2,sep ='')

a :[[1 2 3]
 [4 5 6]
 [7 8 9]]
b :[[2 2 2]
 [2 2 2]
 [2 2 2]]
a+b:[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a-b:[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
a*b:[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
a/b:[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
a@b:[[12 12 12]
 [30 30 30]
 [48 48 48]]
a**2:[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
#lab 11-4
#1

a1 = np.full((3,3),2)
a1 = repr(a1)
print('a1=',a1,sep = '')

#2

a2 = np.arange(1,13)

print('a2=',a2,sep = '')

#3

a3 = np.arange(3,50,3)
print('a3=',a3,sep = '')

#4

a4 = np.linspace(0,20,5)

print('a4=',a4)


a1=array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])
a2=[ 1  2  3  4  5  6  7  8  9 10 11 12]
a3=[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
a4= [ 0.  5. 10. 15. 20.]


In [ ]:
#lab 11-5
#1
a1 = np.arange(1,13)

a1 = a1.reshape(2,6)
print('a1:',a1)

#2
a2 = np.arange(1,31).reshape(3,10)
print('a2:',a2)

#3

a3 = a2.reshape(6,5)
print('a3:',a3)

#4

a4 = np.transpose(a3)

print('a4:',a4)




a1: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a2: [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
a3: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
a4: [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [ ]:
#lab 11-6
#1
a = np.random.randint(1,100,size = 15).reshape(3,5)

print('a:',a)

#2

print('a의 열방향 최솟값 :',a.min(axis=0))
print('a의 열방향 최댓값 :',a.max(axis=0))
print('a의 열방향 평균 :',a.sum(axis=0)/5)

#3

print('a의 행방향 최솟값 :',a.min(axis=1))
print('a의 행방향 최댓값 :',a.max(axis=1))
print('a의 행방향 평균 :',a.sum(axis=1)/5)


a: [[58 20  5 86 39]
 [25 23 60 30 87]
 [10 93 38 93 26]]
a의 열방향 최솟값 : [10 20  5 30 26]
a의 열방향 최댓값 : [58 93 60 93 87]
a의 열방향 평균 : [18.6 27.2 20.6 41.8 30.4]
a의 행방향 최솟값 : [ 5 23 10]
a의 행방향 최댓값 : [86 87 93]
a의 행방향 평균 : [41.6 45.  52. ]


In [ ]:
#lab 11-7

#1

a = np.arange(1,11)
print('a =',a)
b = a[1:9:2]
print('b =',b)

#2

b = a[5::]
print('b =',b)
c = a[6::]
print('c =',c)
d = a[:3:]
print('d =',d)
e = a[::2]
print('e =',e)
f = a[::-2]
print('f =',f)


a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]
b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


In [ ]:
#lab 11-8
#1

a = np.arange(0,24).reshape(4,3,2)

print(a)

# 1번은 잘 이해가 가지 않습니다



#2

#2-1
print(np.concatenate((a[0,0],a[1,0]),axis = 0))

#2-2
print(np.concatenate((a[0,0],a[2,1]),axis = 0))

#2-3
print(np.concatenate((a[0,0],a[0,1],a[0,2],a[1,0],a[1,1],a[1,2]),axis = 0).reshape(6,2))

#2-4
print(np.concatenate((a[0,0],a[1,0],a[0,1],a[1,1],a[0,2],a[1,2]),axis = 0).reshape(3,4))



[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[0 1 6 7]
[ 0  1 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [ ]:
#lab 11-9
#1
a = np.arange(0,16).reshape(4,4)

print('a =',a)

b = a[0:4,1]

print('b =',b )

c = a[2,1:4]
print('c =',c)

d = a[:2,:2]
print('d =',d)

e = a[1:3,1:3]
print('e =',e)

#2


a = a1.reshape(16,1)
f = a1[0,0:7]

print('f =',f)

g = a1[0,8:16]

print('g =',g)

h = np.append(a1[0,5:8], a1[0,13:16])
print('h =',h)

a = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]
f = [0 1 2 3 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [ ]:
a = np.array([1,2,3])
#print(a)
#a.shape
#a.dtype
a

array([1, 2, 3])